name: Pass Array of Values

on: [push]

jobs:
  pass-array-values:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up string and split into array
      id: split_string
      run: |
        input_string="This
        is
        a
        sample
        string"
        array=()
        while IFS= read -r line; do
          array+=("$line")
        done <<< "$input_string"
        echo "array="${array[@]}"" >> $GITHUB_ENV
        # IFS=' ' read -r -a array <<< "$input_string"
        
        # Join array elements with a comma and write to environment file
        # array_output=$(printf "%s," "${array[@]}")
        # echo "array=${array_output%,}" >> $GITHUB_ENV
        # echo "array=$input_string" >> $GITHUB_ENV
    - name: Access array from environment file
      if: contains(env.array, 'is')
      run: |
        # Access the array from the environment file
        array="${array}"
        
        # Convert the comma-separated string back into an array
        IFS=',' read -r -a array <<< "$array"
        
        # Print each element of the array
        for element in "${array[@]}"
        do
          echo "$element"
        done
